use_frameworks!

platform :ios, '9.0'

target 'publicCococpodsLibrary_Example' do
  pod 'publicCococpodsLibrary', :path => '../'

  target 'publicCococpodsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
